### ISSUE TITLE
Checkout button not working

### ISSUE THREAD

**Issue by errordeveloper** [microservices-demo/front-end#42]
A user said to me on Slack:
> I noticed a change in behavior though, if I manually log into the user as user, and try to place an order (using the Proceed to checkout button), I'm seeing I don't get an "order placed" screen. I also don't see orders in the accounts section. Is this intentional, or another bug?

I've also noticed it myself the other day.

May be we could fix it along with https://github.com/microservices-demo/front-end/issues/24?

**Comment by errordeveloper** [comment]
@pidster I'd like to fix it, but will do with a little bit of help, as I'm not familiar with the code.

**Comment by errordeveloper** [comment]
Ok, so `POST /orders` gives a 500...

**Comment by errordeveloper** [comment]
I fail to find any recent changes that could relate to this, I looked in this repo as well as the orders repo...

**Comment by errordeveloper** [comment]
I've started working on this https://github.com/microservices-demo/front-end/pull/43, but still need help understanding how it's supposed to work.

**Comment by dirkwall** [comment]
Hi, I stumbled upon a similar problem today - getting a 500 error when clicking on "Proceed to checkout". My analysis showed, that the call to the orders service uses the wrong IP address.

For my setup I used Docker Compose on a large VM in AWS. As I understand it, the Docker DNS is used for resolving IP addresses of services. In the front-end container the orders service IP address is correctly resolved to 172.19.0.8, in my case. Although when I use the web UI to place products in the cart and proceed to checkout, the POST request to the orders service goes to the public IP address of the server (52.15.xx.xx), not the internal IP address (172.19.0.8).
 
![atejt](https://cloud.githubusercontent.com/assets/15996364/21353788/df800128-c6c7-11e6-8532-6d6ef8ef179c.png)

Hence, the 500 error should therefore come from the edge-router component.
I hope this helps identifying the issue - I will continue to investigate this.

**Comment by dirkwall** [comment]
If I add something like this in my nginx.conf in the edge-router, the request are forwarded to the orders-service.
`location /orders {
     proxy_pass      http://orders:80;
}`
Although, the request are not properly handled.

**Comment by vlal** [comment]
Closing this as it seems to be working again.

**Comment by lukemarsden** [comment]
See https://github.com/microservices-demo/microservices-demo/issues/439

**Comment by vlal** [comment]
@lukemarsden has the front-end on katacoda been updated? it seems to be running an out of date version of the front-end.

**Comment by lukemarsden** [comment]
Yeah, my comment was for @BenHall. He's updating it Soon (TM). Thanks!
