### ISSUE TITLE
Remove hard-coded keys from yaml files

### ISSUE THREAD

**Issue by abuehrle** [microservices-demo/front-end#95]
We use the travis.yml file for a tutorial and tell people to update this file.  Noticed that the file has hard-coded slack credentials in there, which probably shouldn't be.

**Comment by jasonrichardsmith** [comment]
Those are travis encrypted 
https://docs.travis-ci.com/user/notifications/#Configuring-slack-notifications

**Comment by abuehrle** [comment]
ok great. I wasn't sure. I'll close this then.
